#!/usr/bin/env python3
"""
Parse Mureka API response and generate .lrc lyrics files.

Usage:
    python parse_lyrics.py --response-json '<json_string>'
"""

import json
import sys
import argparse


def format_timestamp(ms: int) -> str:
    """Convert milliseconds to LRC timestamp format [mm:ss.xx]"""
    total_seconds = ms / 1000
    minutes = int(total_seconds // 60)
    seconds = total_seconds % 60
    return f"[{minutes:02d}:{seconds:05.2f}]"


def parse_lyrics_sections(lyrics_sections: list) -> list:
    """Parse lyrics_sections from API response into (timestamp, text) tuples"""
    entries = []
    
    for section in lyrics_sections:
        section_type = section.get("section_type", "")
        section_start = section.get("start", 0)
        
        for line in section.get("lines", []):
            line_start = line.get("start", 0)
            line_text = line.get("text", "").strip()
            
            if line_text:
                entries.append((line_start, f"[{section_type.upper()}]", line_text))
        
        section_end = section.get("end", 0)
        if section_end > section_start:
            entries.append((section_end, f"[/{section_type.upper()}]", ""))
    
    entries.sort(key=lambda x: x[0])
    return entries


def generate_lrc(lyrics_sections: list, title: str = "", artist: str = "", album: str = "") -> str:
    """Generate LRC format string from lyrics_sections"""
    lines = []
    
    lines.append("[ti:]" + title if title else "[ti:]")
    lines.append("[ar:]" + artist if artist else "[ar:]")
    lines.append("[al:]" + album if album else "[al:]")
    lines.append("[by:Generated by Mureka Skill]")
    lines.append("[offset:0]")
    lines.append("")
    
    entries = parse_lyrics_sections(lyrics_sections)
    current_section = ""
    
    for timestamp, section_tag, text in entries:
        if section_tag.startswith("[/") and text == "":
            continue
        
        if section_tag.startswith("[") and not section_tag.startswith("[/"):
            current_section = section_tag
            if text:
                lines.append(format_timestamp(timestamp) + text)
        else:
            if text:
                lines.append(format_timestamp(timestamp) + text)
    
    return "\n".join(lines)


def parse_api_response(response: dict, version_index: int = 0) -> str:
    """Parse API response and generate LRC for specified version"""
    choices = response.get("choices", [])
    
    if not choices:
        raise ValueError("No choices found in response")
    
    if version_index >= len(choices):
        raise ValueError(f"Version {version_index} not found, only {len(choices)} versions available")
    
    choice = choices[version_index]
    lyrics_sections = choice.get("lyrics_sections", [])
    
    return generate_lrc(lyrics_sections)


def main():
    parser = argparse.ArgumentParser(description="Parse Mureka API response to LRC format")

    parser.add_argument("--response-json", help="Direct JSON response string")
    parser.add_argument("--version", type=int, default=0, help="Version index (0-based, default: 0)")
    parser.add_argument("--output", "-o", help="Output .lrc file path")
    parser.add_argument("--title", help="Song title")
    parser.add_argument("--artist", help="Artist name")
    parser.add_argument("--album", help="Album name")
    
    args = parser.parse_args()
    
    if not args.response_json:
        parser.print_help()
        sys.exit(1)
    
    response = json.loads(args.response_json)
    
    lrc_content = parse_api_response(response, args.version)
    
    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(lrc_content)
        print(f"LRC file saved to: {args.output}")
    else:
        print(lrc_content)


if __name__ == "__main__":
    main()
